### ISSUE TITLE
Сделать проверку "на дурака"

### ISSUE THREAD

**Issue by ufadeeva** [NaumovCorp/WorkAssistant#10]
Сделать проверку вносимых значений в табличку. Стоп-тайм не может быть меньше старт-тайм.
При попытке задания кривого времени выводить сообщение с причиной ошибки, не давать сохранять такое редактирование.

Сейчас, если задать, например, старт 7.15, а стоп 7.00, то итоговое время будет 15 минут.
Недоработки 8.45.

**Comment by HAYMbl4** [comment]
Добавил проверку, логика следующая:

Время начала не может быть больше времени окончания, для дня в статусе "Отработал". Для всех остальных случаев такое допустимо. В случае если ловится ситуация с такими некорректными данными, будет выведено соответствующее сообщение и данные в строке сбросятся в первоначальное состояние.

Так же добавил ограничение на выбор минимального часа для времени ухода. Может быть <= часу прихода.

**Comment by ufadeeva** [comment]
Теперь нельзя выставить время окончания рабочего дня меньше времени начала.
Любыми способами нельзя))
Замечаний нет
