### ISSUE TITLE
Продумать отображение статистики по рабочему месяцу

### ISSUE THREAD

**Issue by ufadeeva** [NaumovCorp/WorkAssistant#12]
## by HAYMbl4

Идея сделать цветную строку, которая будет отображать состояние отработанного времени по выбранному месяцу. Над строкой выводить информацию:

1. Отработанном времени.
2. Переработанном/Недоработанном времени.
3. Оставшемся времени.

**Пример:**

![default](https://cloud.githubusercontent.com/assets/6511898/7201781/d7dfd9f8-e513-11e4-8289-9dd089974af6.png)

При нажатии на строку, информация со статистикой об отработанном времени должна скрываться и появляться информация со статистикой об отработанных днях:

1. Общее кол-во рабочих дней.
2. Отработано.
3. Пропущено.
4. Осталось.

**Comment by ufadeeva** [comment]
Замечание.
При создании таблицы на текущий месяц для нового пользователя, все дни до текущего считаются как недоработки. Хотя таблица еще пустая.

**Comment by HAYMbl4** [comment]
Это не баг. Для текущего месяца логика такая:

Все дни до текущего (если текущий в состоянии "Отработан", то включая текущий), считаются как необходимые к отработке. Т.е. Если мы не отметили отработанное время, то весь день считается как недоработка. 
Таблица хоть и пустая, но N-ое кол-во часов уже должно быть отработано и оно будет в недоработках. После заполнения информации о прошедших днях это исправится, придумывать какую то логику для таких ситуаций не вижу смысла.

**Comment by ufadeeva** [comment]
Время в таблице считается верно.
Замечаний нет
