### ISSUE TITLE
Доработать обновление таймера отработанного времени.

### ISSUE THREAD

**Issue by ufadeeva** [NaumovCorp/WorkAssistant#13]
Таймер отработанного времени обновляется сам, только если активна страница приложения.
Если заниматься все-таки делами на работе :) , в не любоваться приложением, то при возвращении на страницу  приложения, отработанное время не обновляется. Приходится обновлять страницу.

**Comment by HAYMbl4** [comment]
@ufadeeva, поправил, попровелял, вроде все гуд теперь.

**Comment by ufadeeva** [comment]
Теперь таймер живет своей полноценной жизнью)
Таск закрываю
