### ISSUE TITLE
Вычисление переработок/недоработок для выходного дня

### ISSUE THREAD

**Issue by HAYMbl4** [NaumovCorp/WorkAssistant#7]
Сейчас выходной день никак не выделяется.. Надо чтобы все рабочее время в выходной день считалось как переработка.

**Comment by HAYMbl4** [comment]
Подумать в сторону иерархии дней, создать абстрактный день и от него от наследовать такие сущности как:

* рабочий день;
* выходной;
* и тд.

в этих сущностях будет переопределено, необходимое время для переработок, на основе которого сервис будет строить свою логику.

**Comment by Bablzz** [comment]
class Day {
 boolean workDay
 boolean freeDay
...
}

и анализировать: если workday = true, freeday=false то обычный рабочий день
если не workday = false и freeday = true=>выходной
если workday = true и freeday= true = переработка

конечно не претендую на истину)

**Comment by HAYMbl4** [comment]
Макс, хочется что то, что потом можно легче зарефакторить. 
В добавок все завязывается не только на полный рабочий день и выходной, есть больше сущностей.

## Из того, что пока пришло в голову

Разделим пока что "День" на следующие понятия:

* Полный рабочий день (ПД);
* Сокращенный день (СД);
* Выходной день (В).

По сути все эти дни, отличаются только кол-вом времени, которое необходимо отработать, к примеру для моей фирмы:

* для ПД = 8.5 часов;
* для СД = 7.5 часов;
* для В = 0 часов;

Таким образом можно пока что отказаться от идеи наследования. А ограничится введением понятия "Тип рабочего дня", сделать **Enum**, аналогично **WorkDayState**.
И в класс **WorkDay** добавить метод, который будет определять, в зависимости от типа дня, время, которое необходимо отработать. Этот метод будет дергаться при расчете переработок/недоработок.
